Repository fesi-05-01/frontend, pull requests merged in 2024-11, with the labels that each got.

#1 프로젝트 기본 세팅
  .codecov.yml
  .commitlintrc.json
  .eslintrc.json
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/default.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/pull_request_template.md
  .github/workflows/test-ci.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.json
  .nvmrc
  .prettierrc.json
  .vscode/extensions.json
  .vscode/settings.json
  app/all-reviews/page.tsx
  app/api/sentry-example-api/route.ts
  app/gatherings/[id]/page.tsx
  app/gatherings/page.tsx
  app/global-error.tsx
  app/layout.tsx
  app/login/page.tsx
  app/mypage/page.tsx
  app/page.test.tsx
  app/sentry-example-page/page.tsx
  app/signup/page.tsx
  app/wishlist/page.tsx
  cypress.config.ts
  cypress/e2e/home.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  instrumentation.ts
  jest.config.ts
  jest.setup.ts
  next.config.mjs
  package-lock.json
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  tailwind.config.ts
Labels: chore

#3 chore: tailwind 설정 및 폰트 설정
  app/layout.tsx
  package-lock.json
  package.json
  src/fonts/Pretendard-Bold.woff
  src/fonts/Pretendard-Bold.woff2
  src/fonts/Pretendard-Light.woff
  src/fonts/Pretendard-Light.woff2
  src/fonts/Pretendard-Medium.woff
  src/fonts/Pretendard-Medium.woff2
  src/fonts/Pretendard-Regular.woff
  src/fonts/Pretendard-Regular.woff2
  src/fonts/Pretendard-SemiBold.woff
  src/fonts/Pretendard-SemiBold.woff2
  src/fonts/fonts.ts
  src/utils/class-name.ts
  tailwind.config.ts
Labels: chore

#10 fix: husky error 수정
  .husky/commit-msg
  .husky/pre-commit
  package.json
Labels: fix

#12 아이콘 및 이미지 추가, 평점 컴포넌트 추가
  @types/svgr.d.ts
  next.config.mjs
  package-lock.json
  package.json
  src/assets/icons/alarm.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/bye.svg
  src/assets/icons/caret-down-inverse.svg
  src/assets/icons/caret-down.svg
  src/assets/icons/caret-left.svg
  src/assets/icons/caret-right.svg
  src/assets/icons/caret-up.svg
  src/assets/icons/check.svg
  src/assets/icons/checkbox.tsx
  src/assets/icons/circle-bye.svg
  src/assets/icons/circle-check.tsx
  src/assets/icons/circle-edit.svg
  src/assets/icons/dalaemfit.svg
  src/assets/icons/heart.tsx
  src/assets/icons/person.svg
  src/assets/icons/rectangle-bye.svg
  src/assets/icons/save.tsx
  src/assets/icons/sort-inverse.svg
  src/assets/icons/sort.svg
  src/assets/icons/visibility.tsx
  src/assets/icons/workation.svg
  src/assets/icons/x.svg
  src/assets/images/bg-login.png
  src/assets/images/bg-profile.png
  src/assets/images/head-class.png
  src/assets/images/head-review.png
  src/assets/images/head-saved.png
  src/assets/images/logo-large.png
  src/assets/images/logo-small.png
  src/assets/images/mypage-profile-edit.png
  src/assets/images/mypage-profile.png
  src/assets/images/profile-large.png
  src/assets/images/profile-small.png
  src/components/common/rating.tsx
  tsconfig.json
Labels: feat

#22 fix: jest, cypress 타입 에러 수정
  tsconfig.json
Labels: fix

#16 모달 공통 컴포넌트 생성
  package-lock.json
  package.json
  src/components/common/modal.tsx
Labels: feat

#18 인풋 컴포넌트 구현
  package-lock.json
  package.json
  src/components/calender/calender.tsx
  src/components/common/button.tsx
  src/components/common/input.tsx
  src/components/common/textarea.tsx
  tailwind.config.ts
Labels: feat

#24 feat: 필터와 드롭다운 컨포넌트
  app/example/page.tsx
  src/components/common/dropdown.tsx
  src/components/common/filter.tsx
Labels: feat

#29 레이아웃 css 구현
  app/layout.tsx
  app/page.tsx
  src/components/layout/floating-bar.tsx
  src/components/layout/header.tsx
  src/components/layout/main-container.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: feat

#35 axios, tanstack query 설정
  app/all-reviews/page.tsx
  app/layout.tsx
  package-lock.json
  package.json
  src/components/all-reviews/review-list.tsx
  src/components/all-reviews/review-score.tsx
  src/providers/tanstack-query-provider.tsx
  src/services/api.ts
  src/services/auths/.gitkeep
  src/services/gatherings/.gitkeep
  src/services/reviews/queryKey.ts
  src/services/reviews/types.ts
  src/services/reviews/use-create-review.ts
  src/services/reviews/use-get-review-list.ts
  src/services/reviews/use-get-review-score.ts
  src/services/tanstack-query.ts
  src/services/types.ts
Labels: feat

#34 필터와 드롭다운 반응형 개선
  src/components/common/dropdown.tsx
  src/components/common/filter.tsx
Labels: fix

#31 box-select 컨포넌트 작성
  app/example/page.tsx
  src/components/common/box-select.tsx
Labels: feat

#45 feat: input 에러 수정
  src/components/common/input.tsx
Labels: refactor, fix

#40 모임 페이지의 카드 컴포넌트 구현
  app/gatherings/page.tsx
  package-lock.json
  package.json
  public/IMG_1053.jpg
  public/IMG_1190.jpg
  src/assets/icons/person.svg
  src/components/common/member-count-chip.tsx
  src/components/common/progress-bar.tsx
  src/components/common/tag.tsx
  src/components/gathering-card/chip-info-container.tsx
  src/components/gathering-card/closed-button.tsx
  src/components/gathering-card/confirmation.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/join-now-button.tsx
  src/components/gathering-card/type-props.ts
  src/components/gathering-card/use-gathering-card.ts
  src/services/gatherings/types.ts
  src/utils/breakpoints.ts
  src/utils/format-date-time.ts
  tailwind.config.ts
Labels: feat, chore

#49 fix: 공통 컴포넌트 확장성 수정
  src/components/common/badge.tsx
  src/components/common/chip-info.tsx
  src/components/common/chip-state.tsx
  src/components/common/chip-time.tsx
  src/components/common/chip.tsx
Labels: fix

#50 Mypagecard
  app/mypage/page.tsx
  src/components/common/box-select.tsx
  src/components/common/dropdown.tsx
  src/components/common/filter.tsx
  src/components/mypage/group-card.tsx
  src/components/mypage/profile-card.tsx
Labels: fix
