Repository fesi-05-01/frontend, pull requests merged in 2024-12, with the labels that each got.

#51 모든 리뷰 페이지 컴포넌트 작업
  app/all-reviews/page.tsx
  app/layout.tsx
  app/wishlist/page.tsx
  package-lock.json
  package.json
  src/assets/icons/dalaemfit.svg
  src/assets/icons/workation.svg
  src/components/all-reviews/review-gathering-tab.tsx
  src/components/all-reviews/review-score.tsx
  src/components/common/chip.tsx
  src/components/common/gathering-tab/index.tsx
  src/components/common/gathering-tab/main-tab.tsx
  src/components/common/gathering-tab/sub-tab.tsx
  src/components/common/page-title-with-image.tsx
  src/hooks/use-review-filter-atom.ts
  src/providers/jotai-provider.tsx
  src/services/reviews/types.ts
  src/stores/review-filter-atom.ts
Labels: feat, refactor, chore

#56 fix: button.tsx 수정
  src/components/common/button.tsx
Labels: design

#59 모임 찾기 페이지 레이아웃
  app/gatherings/page.tsx
  src/components/gathering-card/card-container.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
Labels: feat

#60 모든 리뷰 페이지 2차 작업 (컴포넌트 마무리, API 로직 연결)
  app/all-reviews/page.tsx
  src/components/all-reviews/review-list.tsx
  src/components/common/progress-bar.tsx
  src/components/reviews/review-card-item.tsx
  src/components/reviews/review-container.tsx
  src/components/reviews/review-gathering-tab.tsx
  src/components/reviews/review-list.tsx
  src/components/reviews/review-score.tsx
  src/hooks/reviews/use-review-filter-atom.ts
  src/services/reviews/queryKey.ts
  src/services/reviews/types.ts
  src/services/reviews/use-get-review-infinite-list.ts
  src/services/reviews/use-get-review-list.ts
  src/services/reviews/use-get-review-score.ts
  src/services/tanstack-query.ts
  src/services/types.ts
Labels: feat, refactor, fix

#64 fix: 경로 변경
  app/gatherings/page.tsx
Labels: fix

#54 공통 커포넌트 사이즈 적용 오류 수정 및 필터와 드롭다운 수정
  app/example/page.tsx
  app/gatherings/page.tsx
  src/components/common/box-select.tsx
  src/components/common/calendar-dropdown.tsx
  src/components/common/dropdown.tsx
  src/components/common/filter.tsx
  src/components/common/left-filter.tsx
  src/components/common/right-filter.tsx
Labels: fix

#65 MSW 세팅
  app/layout.tsx
  instrumentation.ts
  next.config.mjs
  package-lock.json
  package.json
  public/.gitkeep
  public/mockServiceWorker.js
  src/components/reviews/review-list.tsx
  src/mocks/browser.ts
  src/mocks/handler/auths.ts
  src/mocks/handler/gatherings.ts
  src/mocks/handler/reviews.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/mocks/utils.ts
  src/providers/msw-provider.tsx
  src/providers/tanstack-query-provider.tsx
  src/services/api.ts
Labels: feat, refactor, chore

#61 fix: 회원가입 구현
  app/login/page.tsx
  app/mypage/page.tsx
  app/signup/page.tsx
  middleware.ts
  package-lock.json
  package.json
  src/components/authpage/auth-formcard.tsx
  src/components/authpage/authpage-bg.tsx
  src/components/authpage/login-form.tsx
  src/components/authpage/signup-form.tsx
  src/components/authpage/types.ts
  src/components/authpage/validation/auth-schemas.ts
  src/components/common/active-link.tsx
  src/components/common/gnb.tsx
  src/components/common/profile-dropdown.tsx
  src/components/layout/header.tsx
  src/services/api.ts
  src/services/auths/use-login.ts
  src/services/auths/use-logout.ts
  src/services/auths/use-signup.ts
  src/store/auth-store.ts
Labels: feat

#70 모임 상세 페이지
  app/gatherings/[id]/page.tsx
  next.config.mjs
  package-lock.json
  package.json
  src/components/gathering-card/card-container.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/gathering-detail-image.tsx
  src/components/gathering-card/gathering-info.tsx
  src/components/gathering-card/gathering-profile-images.tsx
  src/components/gathering-card/gathering-review-list.tsx
  src/components/gathering-card/type-props.ts
  src/hooks/gatherings/use-gathering-card.ts
  src/mocks/faker/fake-gathering-participants.ts
  src/mocks/faker/fake-gatherings.ts
  src/mocks/faker/fake-user.ts
  src/mocks/handler/gatherings.ts
  src/services/gatherings/.gitkeep
  src/services/gatherings/queryKey.ts
  src/services/gatherings/types.ts
  src/services/gatherings/use-gathering-detail.ts
  src/services/gatherings/use-gathering-participants.ts
  src/services/gatherings/use-gathering-review.ts
  src/utils/is-registration-ended.ts
Labels: feat

#71 모임 만들기 모달 작업
  app/gatherings/page.tsx
  package-lock.json
  package.json
  src/components/common/box-select.tsx
  src/components/common/button.tsx
  src/components/common/chip-time.tsx
  src/components/common/scroll-area.tsx
  src/components/gatherings/create-gathering-modal/form-calendar.tsx
  src/components/gatherings/create-gathering-modal/form-gathering-type.tsx
  src/components/gatherings/create-gathering-modal/form-hour-picker.tsx
  src/components/gatherings/create-gathering-modal/form-image.tsx
  src/components/gatherings/create-gathering-modal/form-location.tsx
  src/components/gatherings/create-gathering-modal/index.tsx
  src/components/gatherings/create-gathering-modal/schema.ts
  src/services/gatherings/types.ts
  src/services/gatherings/use-create-gathering.ts
  src/utils/date.ts
Labels: feat, refactor, fix, chore

#76 fix: 파일위치 변경 & 마이페이지 프로필 카드 & 겟 유저
  package-lock.json
  package.json
  src/components/common/avatar.tsx
  src/components/common/profile-dropdown.tsx
  src/components/common/profile-image-upload.tsx
  src/components/layout/header.tsx
  src/components/mypage/profile-card.tsx
  src/components/mypage/profile-edit.tsx
  src/services/auths/edit-user.ts
  src/services/auths/get-user.ts
  src/services/auths/types.ts
  src/services/auths/use-login.ts
  src/services/auths/use-logout.ts
  src/services/auths/use-signup.ts
  src/stores/auth-store.ts
Labels: feat

#80 버셀 배포를 위한 준비 단계
  .github/workflows/test-ci.yml
  .gitignore
  app/layout.tsx
  package-lock.json
  package.json
  src/components/gatherings/create-gathering-modal/index.tsx
  src/providers/msw-provider.tsx
  src/services/api.ts
Labels: fix, chore

#82 배포 관련 CI 추가
  .github/workflows/synchronize-forked-repo.yaml
Labels: chore

#84 v0.1.1
  .github/workflows/synchronize-forked-repo.yaml
Labels: release

#85 모임찾기 페이지
  app/gatherings/page.tsx
  src/components/common/left-filter.tsx
  src/components/common/right-filter.tsx
  src/components/gathering-card/card-container.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/gathering-panel.tsx
  src/hooks/gatherings/use-gathering-filter.ts
  src/mocks/faker/fake-gatherings.ts
  src/mocks/faker/fake-user.ts
  src/mocks/handler/gatherings.ts
  src/services/gatherings/queryKey.ts
  src/services/gatherings/types.ts
  src/services/gatherings/use-gatherings.ts
  src/stores/gathering-filter-atom.ts
Labels: feat

#86 토스트 추가 및 공통 세팅 css 값 수정
  app/layout.tsx
  package-lock.json
  package.json
  src/components/common/modal.tsx
  src/components/gatherings/create-gathering-modal/index.tsx
  src/providers/toast-provider.tsx
  src/services/api.ts
Labels: design, chore

#89 찜하기 기능
  app/wishlist/page.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/gathering-info.tsx
  src/components/wishlist/wishlist-container.tsx
  src/components/wishlist/wishlist-panel.tsx
  src/hooks/gatherings/use-gathering-card.ts
  src/hooks/wishlist/use-wishlist.ts
  src/mocks/handler/gatherings.ts
  src/stores/wishlist-atom.ts
Labels: feat

#90 모든 리뷰 페이지 마무리 작업
  app/all-reviews/page.tsx
  app/layout.tsx
  package-lock.json
  package.json
  src/components/common/right-filter.tsx
  src/components/reviews/review-filter.tsx
  src/components/reviews/review-list.tsx
  src/hooks/reviews/use-review-filter-atom.ts
  src/mocks/handler/reviews.ts
  src/providers/navigation-provider.tsx
  src/services/reviews/types.ts
  src/services/reviews/use-get-review-infinite-list.ts
  src/stores/review-filter-atom.ts
  src/utils/date.ts
Labels: refactor, fix, chore

#95 리뷰 쓰기 모달 추가
  app/all-reviews/page.tsx
  src/components/common/rating.tsx
  src/components/common/textarea.tsx
  src/components/mypage/group-card.tsx
  src/components/reviews/all-reviews-page/review-container.tsx
  src/components/reviews/all-reviews-page/review-filter.tsx
  src/components/reviews/all-reviews-page/review-gathering-tab.tsx
  src/components/reviews/all-reviews-page/review-list.tsx
  src/components/reviews/all-reviews-page/review-score.tsx
  src/components/reviews/create-review-modal/index.tsx
  src/components/reviews/create-review-modal/schema.ts
Labels: feat, refactor

#97 상세페이지 페이지네이션
  app/gatherings/[id]/page.tsx
  cypress/e2e/home.cy.ts
  middleware.ts
  src/components/gathering-card/card-container.tsx
  src/components/gathering-card/gathering-detail-content.tsx
  src/components/gathering-card/gathering-profile-images.tsx
  src/components/gathering-card/gathering-review-list.tsx
  src/components/gathering-card/more-horizontal.tsx
  src/components/gathering-card/pagination.tsx
  src/components/reviews/all-reviews-page/review-list.tsx
  src/components/reviews/review-card-item.tsx
  src/mocks/handler/reviews.ts
  src/services/gatherings/use-gathering-detail.ts
  src/services/gatherings/use-gathering-review.ts
  src/services/reviews/types.ts
  src/services/reviews/use-get-review-infinite-list.ts
  src/utils/breakpoints.ts
Labels: feat, refactor

#102 모임 페이지 애니메이션
  src/assets/icons/save.tsx
  src/components/common/member-count-chip.tsx
  src/components/common/progress-bar.tsx
  src/components/gathering-card/card-container.tsx
  src/components/gathering-card/gathering-info.tsx
  src/components/gathering-card/gathering-panel.tsx
  src/components/gathering-card/gathering-profile-images.tsx
  src/components/layout/floating-bar.tsx
  src/hooks/gatherings/use-count-animation.ts
  src/mocks/faker/fake-gatherings.ts
  src/mocks/faker/fake-user.ts
  src/mocks/handler/gatherings.ts
  src/services/gatherings/types.ts
  src/services/gatherings/use-gathering-participants.ts
Labels: feat

#106 msw onoff 추가
  instrumentation.ts
  src/providers/msw-provider.tsx
Labels: feat, chore

#110 리뷰 작성, 모임 만들기 로직 수정
  src/components/gatherings/create-gathering-modal/contents-form.tsx
  src/services/gatherings/use-create-gathering.ts
  src/services/reviews/queryKey.ts
  src/services/reviews/use-create-review.ts
Labels: refactor

#120 모든 리뷰 페이지 수정
  app/all-reviews/page.tsx
  src/components/reviews/all-reviews-page/review-list.tsx
  src/stores/review-filter-atom.ts
Labels: refactor, design

#128 test: 테스트 전역 모킹 설정 및 테스트 작성
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/components/common/chip-info.test.tsx
  src/components/common/member-count-chip.test.tsx
  src/components/common/progress-bar.test.tsx
  src/components/common/progress-bar.tsx
  src/components/common/tag.test.tsx
  src/components/gathering-card/chip-info-container.test.tsx
  src/components/gathering-card/closed-button.test.tsx
  src/components/gathering-card/confirmation.test.tsx
  src/components/gathering-card/gathering-card-large.test.skip.tsx
  src/components/gathering-card/gathering-info.tsx
  src/components/gathering-card/join-now-button.test.tsx
  src/hooks/gatherings/use-count-animation.test.skip.ts
  src/hooks/gatherings/use-count-animation.ts
  src/hooks/gatherings/use-gathering-card.test.ts
  src/mocks/fileMock.js
  src/mocks/svgrMock.js
  src/utils/format-date-time.test.ts
  src/utils/format-date-time.ts
  src/utils/is-registration-ended.test.ts
  src/utils/is-registration-ended.ts
  tsconfig.json
Labels: fix, test

#130 드롭다운 이슈 수정
  src/components/common/calendar-dropdown.tsx
  src/components/common/profile-dropdown.tsx
Labels: refactor, design

#134 모임 만들기 모달 수정
  package-lock.json
  package.json
  src/assets/icons/calendar.svg
  src/components/common/join-toggle-button.tsx
  src/components/common/pop-over.tsx
  src/components/common/scroll-area.tsx
  src/components/gatherings/create-gathering-modal/contents-form.tsx
  src/components/gatherings/create-gathering-modal/form-calendar.tsx
  src/components/gatherings/create-gathering-modal/form-date.tsx
  src/components/gatherings/create-gathering-modal/form-hour-picker.tsx
  src/components/gatherings/create-gathering-modal/index.tsx
  src/components/gatherings/create-gathering-modal/schema.ts
  src/services/gatherings/use-create-gathering.ts
  src/services/gatherings/use-join-gathering.ts
  src/utils/date.ts
Labels: feat, refactor, design

#135 마이페이지 api 연결
  app/mypage/page.tsx
  src/components/mypage/data-render.tsx
  src/components/mypage/group-card.tsx
  src/components/mypage/tab-bottom.tsx
  src/components/mypage/tab-top.tsx
  src/services/mypage/queryKey.ts
  src/services/mypage/types.ts
  src/services/mypage/use-get-joined-gatherings-infinite.ts
  src/stores/my-page-atoms.ts
Labels: feat, refactor, design

#137 v0.4.0
  app/mypage/page.tsx
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/assets/icons/calendar.svg
  src/components/common/button.test.tsx
  src/components/common/calendar-dropdown.tsx
  src/components/common/cancel-gathering-button.tsx
  src/components/common/chip-info.test.tsx
  src/components/common/join-toggle-button.tsx
  src/components/common/member-count-chip.test.tsx
  src/components/common/pop-over.tsx
  src/components/common/profile-dropdown.tsx
  src/components/common/progress-bar.test.tsx
  src/components/common/progress-bar.tsx
  src/components/common/scroll-area.tsx
  src/components/common/tag.test.tsx
  src/components/gathering-card/chip-info-container.test.tsx
  src/components/gathering-card/closed-button.test.tsx
  src/components/gathering-card/confirmation.test.tsx
  src/components/gathering-card/gathering-card-large.test.skip.tsx
  src/components/gathering-card/gathering-detail-content.tsx
  src/components/gathering-card/gathering-info.tsx
  src/components/gathering-card/join-now-button.test.tsx
  src/components/gatherings/create-gathering-modal/contents-form.tsx
  src/components/gatherings/create-gathering-modal/form-calendar.tsx
  src/components/gatherings/create-gathering-modal/form-date.tsx
  src/components/gatherings/create-gathering-modal/form-hour-picker.tsx
  src/components/gatherings/create-gathering-modal/index.tsx
  src/components/gatherings/create-gathering-modal/schema.ts
  src/components/layout/floating-bar.tsx
  src/components/mypage/data-render.tsx
  src/components/mypage/group-card.tsx
  src/components/mypage/tab-bottom.tsx
  src/components/mypage/tab-top.tsx
  src/hooks/gatherings/use-count-animation.test.skip.ts
  src/hooks/gatherings/use-count-animation.ts
  src/hooks/gatherings/use-gathering-card.test.ts
  src/mocks/fileMock.js
  src/mocks/svgrMock.js
  src/providers/toast-provider.tsx
  src/services/auths/get-user.ts
  src/services/gatherings/use-cancel-gathering.ts
  src/services/gatherings/use-create-gathering.ts
  src/services/gatherings/use-join-gathering.ts
  src/services/gatherings/use-joined-gathering.ts
  src/services/gatherings/use-leave-gathering.ts
  src/services/mypage/queryKey.ts
  src/services/mypage/types.ts
  src/services/mypage/use-get-joined-gatherings-infinite.ts
  src/stores/my-page-atoms.ts
  src/utils/date.ts
  src/utils/format-date-time.test.ts
  src/utils/format-date-time.ts
  src/utils/is-registration-ended.test.ts
  src/utils/is-registration-ended.ts
  tsconfig.json
Labels: release

#140 fix: 한국 시간대로 고정
  package.json
  src/components/gathering-card/chip-info-container.test.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/gathering-detail-image.tsx
  src/components/gathering-card/gathering-profile-images.tsx
  src/mocks/faker/fake-gatherings.ts
  src/mocks/handler/gatherings.ts
  src/utils/date.ts
  src/utils/format-date-time.test.ts
  src/utils/format-date-time.ts
Labels: bug

#143 test: 모임 카드 컴포넌트 테스트 코드 추가
  jest.setup.ts
  src/assets/icons/save.tsx
  src/components/common/member-count-chip.test.tsx
  src/components/common/member-count-chip.tsx
  src/components/gathering-card/gathering-card-large.test.skip.tsx
  src/components/gathering-card/gathering-card-large.test.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.test.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/hooks/gatherings/use-count-animation.test.skip.ts
Labels: test

#145 fix: 시간대 수정과 카드에 타입 추가
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/gathering-type-container.tsx
  src/utils/date.ts
Labels: feat, fix

#149 날짜 함수 관련 테스트 코드 추가
  src/services/gatherings/use-create-gathering.ts
  src/utils/date.test.ts
  src/utils/date.ts
Labels: refactor, test

#150 v0.4.2
  .env.development
  .env.production
  .gitignore
  jest.setup.ts
  src/assets/icons/save.tsx
  src/components/authpage/ signup-form.test.tsx
  src/components/authpage/login-form.test.tsx
  src/components/authpage/login-form.tsx
  src/components/authpage/signup-form.tsx
  src/components/authpage/validation/auth-schema.test.tsx
  src/components/authpage/validation/auth-schemas.ts
  src/components/common/avatar.tsx
  src/components/common/member-count-chip.test.tsx
  src/components/common/member-count-chip.tsx
  src/components/gathering-card/chip-info-container.test.tsx
  src/components/gathering-card/gathering-card-large.test.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.test.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/gathering-detail-image.tsx
  src/components/gathering-card/gathering-profile-images.tsx
  src/components/gathering-card/gathering-type-container.tsx
  src/components/mypage/profile-edit.tsx
  src/mocks/faker/fake-gatherings.ts
  src/mocks/handler/gatherings.ts
  src/services/gatherings/use-create-gathering.ts
  src/utils/date.test.ts
  src/utils/date.ts
  src/utils/format-date-time.test.ts
  src/utils/format-date-time.ts
Labels: release

#151 리뷰 관련 테스트 코드 추가
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/assets/icons/heart.test.tsx
  src/assets/icons/heart.tsx
  src/components/common/rating.test.tsx
  src/components/common/rating.tsx
  src/components/reviews/all-reviews-page/review-gathering-tab.test.tsx
  src/components/reviews/all-reviews-page/review-score.test.tsx
  src/components/reviews/review-card-item.test.tsx
  src/components/reviews/review-card-item.tsx
  src/hooks/reviews/use-review-filter-atom.test.ts
  src/mocks/handler/reviews.json
  src/mocks/handler/reviews.ts
  src/services/reviews/use-get-review-score.test.ts
  src/utils/wrapper.tsx
Labels: test

#152 공통 컨포넌트 테스트
  package-lock.json
  package.json
  src/components/common/calendar-dropdown.test.tsx
  src/components/common/calendar-dropdown.tsx
  src/components/common/dropdown.test.tsx
  src/components/common/left-filter.test.tsx
  src/components/common/left-filter.tsx
  src/components/common/right-filter.test.tsx
  src/components/common/right-filter.tsx
  src/components/mypage/group-card.test.tsx
  src/components/mypage/tab-bottom.test.tsx
  src/components/mypage/tab-top.test.tsx
  src/services/mypage/use-get-joined-gatherings-infinite.ts
Labels: feat

#157 test: 찜 테스트 및 약간의 수정
  src/components/gathering-card/gathering-card-large.test.skip.tsx
  src/components/gathering-card/gathering-card-large.tsx
  src/components/gathering-card/gathering-card-small.tsx
  src/components/gathering-card/gathering-detail-content.test.tsx
  src/components/gathering-card/gathering-info.test.tsx
  src/components/gathering-card/gathering-panel.test.tsx
  src/components/gathering-card/gathering-review-list.test.tsx
  src/components/wishlist/wishlist-container.test.tsx
  src/components/wishlist/wishlist-panel.tsx
  src/hooks/wishlist/use-wishlist.test.ts
Labels: fix, test

#161 fix: 라우터 모킹 수정
  src/components/gathering-card/gathering-card-large.test.tsx
  src/components/gathering-card/gathering-card-small.test.tsx
Labels: test

#162 모임 만들기 모달 리팩토링
  package-lock.json
  package.json
  src/components/common/drawer.tsx
  src/components/gatherings/create-gathering-modal/form-date.tsx
  src/components/gatherings/create-gathering-modal/form-date/date-picker.tsx
  src/components/gatherings/create-gathering-modal/form-date/index.tsx
  src/components/gatherings/create-gathering-modal/form-date/time-picker.tsx
  src/components/gatherings/create-gathering-modal/form-date/trigger.tsx
  src/components/reviews/all-reviews-page/review-list.test.tsx
  src/components/reviews/create-review-modal/index.test.tsx
  src/components/reviews/create-review-modal/index.tsx
  src/mocks/handler/reviews.test.ts
Labels: refactor, test
